import { computed } from 'vue'
import { useAppStore } from '@/stores/appStore'

const messages = {
  zh: {
    settings: {
      appSettings: '应用设置',
      theme: '主题',
      themeLight: '浅色',
      themeDark: '深色',
      themeSystem: '跟随系统',
      language: '语言',
      globalSettings: '全局设置',
      autoForward: '提及自动转发'
    },
    chat: {
      newChat: '⊕ 新建对话',
      rename: '重命名',
      delete: '删除',
      inputPlaceholder: '输入消息，按回车发送...',
      modelThinking: '模型 {name} 正在思考...',
      send: '发送',
      cancel: '取消',
      confirm: '确认',
      forward: '转发',
      copy: '复制',
      edit: '编辑',
      locked: '已锁定，无法编辑',
      translate: '翻译',
      translating: '翻译中...',
      play: '播放',
      modelSelectTitle: '选择本次对话要使用的模型',
      forwardTitle: '转发到模型',
      setDefault: '在本会话中设为默认',
      selectAtLeastOne: '请选择至少一个模型',
      copied: '已复制',
      copyFailed: '复制失败，请重试',
      translateFailed: '翻译失败，请稍后重试',
      playFailed: '播放失败，请重试',
      from: '来自',
      user: '用户',
      emptyResponse: '（空响应）',
      errorResponse: '模型响应失败，请稍后重试',
      disclaimer: '服务生成的所有内容均由AI生成，其准确性与完整性无法保证，不代表作者的态度或观点'
    }
  },
  en: {
    settings: {
      appSettings: 'App Settings',
      theme: 'Theme',
      themeLight: 'Light',
      themeDark: 'Dark',
      themeSystem: 'System',
      language: 'Language',
      globalSettings: 'Global Settings',
      autoForward: 'Auto-Forward on Mention'
    },
    chat: {
      newChat: '⊕ New Chat',
      rename: 'Rename',
      delete: 'Delete',
      inputPlaceholder: 'Type a message, press Enter to send...',
      modelThinking: 'Model {name} is thinking...',
      send: 'Send',
      cancel: 'Cancel',
      confirm: 'Confirm',
      forward: 'Forward',
      copy: 'Copy',
      edit: 'Edit',
      locked: 'Locked, cannot edit',
      translate: 'Translate',
      translating: 'Translating...',
      play: 'Play',
      modelSelectTitle: 'Select models for this chat',
      forwardTitle: 'Forward to model',
      setDefault: 'Set as default in this chat',
      selectAtLeastOne: 'Please select at least one model',
      copied: 'Copied',
      copyFailed: 'Copy failed, please try again',
      translateFailed: 'Translation failed, please try again',
      playFailed: 'Playback failed, please try again',
      from: 'From',
      user: 'User',
      emptyResponse: '(Empty response)',
      errorResponse: 'Model response failed, please try again later',
      disclaimer: 'All content is generated by AI. Accuracy and completeness are not guaranteed and do not represent the views of the author.'
    }
  },
  ja: {
    settings: {
      appSettings: 'アプリ設定',
      theme: 'テーマ',
      themeLight: 'ライト',
      themeDark: 'ダーク',
      themeSystem: 'システム',
      language: '言語',
      globalSettings: 'グローバル設定',
      autoForward: 'メンション自動転送'
    },
    chat: {
      newChat: '⊕ 新しいチャット',
      rename: '名前を変更',
      delete: '削除',
      inputPlaceholder: 'メッセージを入力、Enterで送信...',
      modelThinking: 'モデル {name} が考え中...',
      send: '送信',
      cancel: 'キャンセル',
      confirm: '確認',
      forward: '転送',
      copy: 'コピー',
      edit: '編集',
      locked: 'ロックされています、編集できません',
      translate: '翻訳',
      translating: '翻訳中...',
      play: '再生',
      modelSelectTitle: 'このチャットで使用するモデルを選択',
      forwardTitle: 'モデルに転送',
      setDefault: 'このチャットでデフォルトに設定',
      selectAtLeastOne: '少なくとも1つのモデルを選択してください',
      copied: 'コピーしました',
      copyFailed: 'コピーに失敗しました。もう一度お試しください',
      translateFailed: '翻訳に失敗しました。後でもう一度お試しください',
      playFailed: '再生に失敗しました。もう一度お試しください',
      from: '送信者',
      user: 'ユーザー',
      emptyResponse: '（空の応答）',
      errorResponse: 'モデルの応答に失敗しました。後でもう一度お試しください',
      disclaimer: '生成されたすべてのコンテンツはAIによって生成されたものであり、その正確性と完全性は保証されず、著者の態度や意見を代表するものではありません'
    }
  }
}

export const useI18n = () => {
  const appStore = useAppStore()
  
  const t = (path, args = {}) => {
    const lang = appStore.language
    const keys = path.split('.')
    let value = messages[lang] || messages['zh']
    
    for (const key of keys) {
      if (value && value[key]) {
        value = value[key]
      } else {
        return path // Fallback to key if not found
      }
    }
    
    if (typeof value === 'string') {
      // Simple interpolation
      Object.keys(args).forEach(key => {
        value = value.replace(`{${key}}`, args[key])
      })
    }
    
    return value
  }

  return { t }
}
